# Save as: swagger.yaml

openapi: 3.0.0
info:
  title: Animated Image Application API
  version: 1.0.0
  description: API for the Animated Image Application

paths:
  /upload:
    post:
      summary: Upload an image
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful upload
          content:
            application/json:    
              schema:
                type: object
                properties:
                  message:
                    type: string
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        class:
                          type: string
                        confidence:
                          type: number
                        bbox:
                          type: array
                          items:
                            type: number
  /health:
    get:
      summary: Check API health
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string